- name: Installing python Server
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: latest

- name: Configuring app-prestartup
  ansible.builtin.include_tasks:
    file: app_prestartup.yml

- name: Installing Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Configuring service_start
  ansible.builtin.include_tasks:
    file: service_start.yml

- name: Configuring {{ component }} service
  ansible.builtin.copy:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Enabling and starting the {{ component }} server
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes