- name: Configuring catalogue service
    src: catalogue.service
    dest: /etc/systemd/system/"{{ component }}".service

- name: Enabling and starting the catalogue server
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes